//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Main.rc
//
#define IDC_MYICON                      2
#define IDD_ABOUTBOX                    103
#define IDS_APP_TITLE                   103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDS_HELLO                       106
#define IDI_Main                        107
#define IDI_SMALL                       108
#define IDC_PRAMFRAME                   109
#define IDD_MainWnd                     129
#define IDD_SpiUartI2cDbg               129
#define IDD_SpiFlash                    130
#define IDD_FlashEepromDbg              130
#define IDD_MainWnd1                    131
#define IDD_JtagDebug                   131
#define IDD_SpiUartI2cDbg1              132
#define IDD_UartDbg                     132
#define IDC_InformationShow             1000
#define IDC_ClearShow                   1002
#define IDC_InforShow                   1003
#define IDC_AboutBox                    1004
#define IDC_ClearInfor                  1005
#define IDC_DeviceList                  1006
#define IDC_TestInterval                1007
#define IDC_DbgOut                      1008
#define IDC_StopPrinter                 1009
#define IDC_VERIFY_BIT                  1010
#define IDC_ObjList                     1011
#define IDC_GetDevConfig                1012
#define IDC_SpiModeSel                  1013
#define IDC_SpiCfg_Mode                 1014
#define IDC_SEARCH                      1015
#define IDC_SpiFreq                     1016
#define IDC_SpiCfg_Clock                1017
#define IDC_ResetDevice                 1018
#define IDC_RefreshObjList              1019
#define IDC_SetDeviceConfig             1020
#define IDC_TxPktLenS                   1021
#define IDC_SpiBitOrder                 1022
#define IDC_SpiCfg_ByteBitOrder         1023
#define IDC_EepromType                  1024
#define IDC_ObjStatusList               1025
#define IDC_SpiCsSel                    1026
#define IDC_SpiCfg_ChipIndex            1027
#define IDC_RestoreDefaultConfig        1028
#define IDC_TxPktLenE                   1029
#define IDC_SpiCsStatus                 1030
#define IDC_Uart_ObjList                1031
#define IDC_JtagTapState                1032
#define IDC_TxInterTime                 1033
#define IDC_SpiCfg_ChipIndex2           1034
#define IDC_Uart_Refresh                1035
#define IDC_SpiCsStatus2                1036
#define IDC_SpiCfg_CS1Polarity          1037
#define IDC_SpiCfg_CS2Polarity          1038
#define IDC_CloseDevice                 1039
#define IDC_RELINK_TIMES                1040
#define IDC_BrowseRxFile                1041
#define IDC_Uart_Close                  1042
#define IDC_FlashIdentify               1043
#define IDC_FlashErase                  1044
#define IDC_FlashRead                   1045
#define IDC_FlashWrite                  1046
#define IDC_FlashAddr                   1047
#define IDC_FlashStartAddr              1048
#define IDC_FlashDataSize               1049
#define IDC_FlashData                   1050
#define IDC_FlashRWSpeedTest            1051
#define IDC_FlashVerify                 1052
#define IDC_TestFilePath                1053
#define IDC_EepromStartAddr             1054
#define IDC_SelectTestFile              1055
#define IDC_EepromDataSize              1056
#define IDC_TestLen                     1057
#define IDC_EepromData                  1058
#define IDC_WriteFormFile               1059
#define IDC_ReadToFile                  1060
#define IDC_SpiCfg_ActiveDelay          1061
#define IDC_EepromRead                  1062
#define IDC_SpiCfg_DelayDeactive        1063
#define IDC_EepromWrite                 1064
#define IDC_EnableCS                    1065
#define IDC_WriteEepromFormFile         1066
#define IDC_AutoDeativeCS               1067
#define IDC_ReadEepromToFile            1068
#define IDC_SpiOut                      1069
#define IDC_SpiIn                       1070
#define IDC_JtagState_Switch            1071
#define IDC_OpenDevice                  1072
#define IDC_CMD_InitSPI                 1073
#define IDC_CMD_SPICsCtrl               1074
#define IDC_CMD_SPIStream               1075
#define IDC_CMD_BulkSpiIn               1076
#define IDC_CMD_BulkSpiOut              1077
#define IDC_Uart_Open                   1078
#define IDC_CMD_I2C_RW                  1079
#define IDC_SetGpio                     1080
#define IDC_GetGpio                     1081
#define IDC_Jtag_ByteWrite              1082
#define IDC_JtagInLen                   1084
#define IDC_JtagIn                      1085
#define IDC_Jtag_ByteRead               1086
#define IDC_JtaShiftgChannel            1087
#define IDC_Jtag_BitRead                1088
#define IDC_Uart_Timeout                1089
#define IDC_Uart_Parity                 1090
#define IDC_Uart_StopBits               1091
#define IDC_Uart_Write                  1092
#define IDC_Uart_DataSize               1093
#define IDC_Uart_WriteData              1094
#define IDC_Uart_Set                    1095
#define IDC_Uart_ReadData               1096
#define IDC_Uart_Read                   1097
#define IDC_JtagOutLenName2             1098
#define IDC_UartSendFile                1098
#define IDC_JtagOutBit                  1099
#define IDC_JtagOutLenName3             1100
#define IDC_TotalCntTRx                 1100
#define IDC_JtagInBit                   1101
#define IDC_ResetCnt                    1101
#define IDC_Jtag_BitWrite               1102
#define IDC_EnAutoRecvToFile            1102
#define IDC_JtagInBitLen                1103
#define IDC_Uart_StopRxThread           1103
#define IDC_EepromVerify                1104
#define IDC_Uart_StopTxThread           1104
#define IDC_JtagOutLen                  1105
#define IDC_DevInfor                    1105
#define IDC_Uart_WriteLen               1106
#define IDC_DevInfor2                   1106
#define IDC_EnablePnPAutoOpen           1106
#define IDC_DevInfor_Jtag               1106
#define IDC_JtagOutBitLen               1107
#define IDC_EnAutoRecvShow              1107
#define IDC_EnablePnPAutoOpen_Flash     1107
#define IDC_Uart_Baudrate               1108
#define IDC_EnablePnPAutoOpen3          1108
#define IDC_EnablePnPAutoOpen_Jtag      1108
#define IDC_PnPStatus                   1108
#define IDC_JtagIfConfig                1109
#define IDC_EnablePnPAutoOpen2          1109
#define IDC_EnablePnPAutoOpen_Uart      1109
#define IDC_PnPStatus_Flash             1109
#define IDC_JtagOutLenName              1110
#define IDC_PnPStatus_Uart              1110
#define IDC_PnPStatus_Jtag              1111
#define IDC_Jtag_InitTarget             1112
#define IDC_EnSet_Gpio0                 1112
#define IDC_Jtag_DnFile_Exam            1113
#define IDC_Dir_Gpio0                   1113
#define IDC_JtagClockRate               1114
#define IDC_Val_Gpio0                   1114
#define IDC_JtagInLenName               1115
#define IDC_EnSet_Gpio1                 1115
#define IDC_DataTransFunc               1116
#define IDC_Dir_Gpio1                   1116
#define IDC_SpiOutLen                   1117
#define IDC_SpiInLen                    1118
#define IDC_SpiCfg_OutInIntervalT       1119
#define IDC_JtagOut                     1120
#define IDC_Val_Gpio1                   1120
#define IDC_Uart_ReadLen                1121
#define IDC_EnSet_Gpio2                 1121
#define IDC_I2COut                      1122
#define IDC_I2CIn                       1123
#define IDC_I2COutLen                   1124
#define IDC_I2CInLen                    1125
#define IDC_Dir_Gpio2                   1126
#define IDC_Val_Gpio2                   1127
#define IDC_EnSet_Gpio3                 1128
#define IDC_Dir_Gpio3                   1129
#define IDC_Val_Gpio3                   1130
#define IDC_EnSet_Gpio4                 1131
#define IDC_Dir_Gpio4                   1132
#define IDC_Val_Gpio4                   1133
#define IDC_EnSet_Gpio5                 1134
#define IDC_Dir_Gpio5                   1135
#define IDC_Val_Gpio5                   1136
#define IDC_EnSet_Gpio6                 1137
#define IDC_Dir_Gpio6                   1138
#define IDC_Val_Gpio6                   1139
#define IDC_EnSet_Gpio7                 1140
#define IDC_Dir_Gpio7                   1141
#define IDC_Val_Gpio7                   1142
#define IDC_GpioEnableAll               1144
#define IDC_GpioSetDirAll               1145
#define IDC_SetDataAll                  1146
#define IDC_GpioSetDataAll              1146

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        102
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1115
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
